implementation of fortify on demand scan

diff --git a/.github/workflows/release-with-jitpack.yml b/.github/workflows/release-with-jitpack.yml
--- a/.github/workflows/release-with-jitpack.yml
+++ b/.github/workflows/release-with-jitpack.yml
@@ -41,4 +41,13 @@ jobs:
             sleep 10
           fi
         done
+
+        echo "::group::Files Available"
+        echo $(cat ${PACKAGES_FILE})
+        echo "::endgroup::"
+
+        if [[ ${STATUS} -gt 399 ]] ; then
+          echo "FAILURE: ${STATUS} response from JitPack"
+          exit 1
+        fi
       if: startsWith(github.ref, 'refs/tags')
