implementation of fortify on demand scan

diff --git a/.github/workflows/release-with-jitpack.yml b/.github/workflows/release-with-jitpack.yml
--- a/.github/workflows/release-with-jitpack.yml
+++ b/.github/workflows/release-with-jitpack.yml
@@ -15,38 +15,38 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v1
-      - name: Set up JDK 11
-        uses: actions/setup-java@v1
-        with:
-          java-version: 11
-      - name: Build
-        run: ./gradlew check
-      - name: Release
-        run: |
-          echo "Triggering JitPack build"
+    - uses: actions/checkout@v1
+    - name: Set up JDK 11
+      uses: actions/setup-java@v1
+      with:
+        java-version: 11
+    - name: Build
+      run: ./gradlew check
+    - name: Release
+      run: |
+        echo "Triggering JitPack build"
 
-          PACKAGES_URL="https://jitpack.io/com/github/${GITHUB_REPOSITORY}/${GITHUB_REF#refs/tags/}/"
-          PACKAGES_FILE="packages.txt"
-          touch ${PACKAGES_FILE}
-          # Try the URL 6 times before failing
-          count=1
-          until [[ $count -gt 6 ]] || grep -q build.log ${PACKAGES_FILE} ; do
-            echo "Attempt ${count}/6"
-            STATUS=$(curl -s -o packages.txt -w "%{http_code}" --max-time 900 ${PACKAGES_URL})
+        PACKAGES_URL="https://jitpack.io/com/github/${GITHUB_REPOSITORY}/${GITHUB_REF#refs/tags/}/"
+        PACKAGES_FILE="packages.txt"
+        touch ${PACKAGES_FILE}
+        # Try the URL 6 times before failing
+        count=1
+        until [[ $count -gt 6 ]] || grep -q build.log ${PACKAGES_FILE} ; do
+          echo "Attempt ${count}/6"
+          STATUS=$(curl -s -o packages.txt -w "%{http_code}" --max-time 900 ${PACKAGES_URL})
 
-            let count+=1
-            if [[ "${STATUS}" -gt 399 ]]; then
-              sleep 30
-            fi
-          done
-
-          echo "::group::Files Available"
-          echo $(cat ${PACKAGES_FILE})
-          echo "::endgroup::"
-
-          if [[ ${STATUS} -gt 399 ]] ; then
-            echo "FAILURE: ${STATUS} response from JitPack"
-            exit 1
+          let count+=1
+          if [[ "${STATUS}" -gt 399 ]]; then
+            sleep 30
           fi
-        if: startsWith(github.ref, 'refs/tags')
+        done
+
+        echo "::group::Files Available"
+        echo $(cat ${PACKAGES_FILE})
+        echo "::endgroup::"
+
+        if [[ ${STATUS} -gt 399 ]] ; then
+          echo "FAILURE: ${STATUS} response from JitPack"
+          exit 1
+        fi
+      if: startsWith(github.ref, 'refs/tags')
